### ISSUE TITLE
Chapter 8: Email address changes (8h) 错误

### ISSUE THREAD

**Issue by VimDong** [VimDong/flaskme#1]
### 错误提示：
TypeError: buffer object expected

#### 详细信息：
```
127.0.0.1 - - [28/May/2016 00:01:58] "GET /auth/change-email HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/Vim/Programs/workspace/virtualenv/flask/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/Vim/Programs/workspace/virtualenv/flask/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/Vim/Programs/workspace/virtualenv/flask/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Vim/Programs/workspace/virtualenv/flask/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Vim/Programs/workspace/virtualenv/flask/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Vim/Programs/workspace/virtualenv/flask/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Vim/Programs/workspace/virtualenv/flask/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Vim/Programs/workspace/virtualenv/flask/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Vim/Programs/workspace/virtualenv/flask/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/Users/Vim/Programs/workspace/flaskme/app/auth/views.py", line 122, in change_email_request
    if current_user.verify_password(form.password.data):
  File "/Users/Vim/Programs/workspace/flaskme/app/models.py", line 34, in verify_password
    return check_password_hash(self.password_hash, password)
  File "/Users/Vim/Programs/workspace/virtualenv/flask/lib/python2.7/site-packages/werkzeug/security.py", line 248, in check_password_hash
    return safe_str_cmp(_hash_internal(method, salt, password)[0], hashval)
  File "/Users/Vim/Programs/workspace/virtualenv/flask/lib/python2.7/site-packages/werkzeug/security.py", line 192, in _hash_internal
    hashfunc=hash_func)
  File "/Users/Vim/Programs/workspace/virtualenv/flask/lib/python2.7/site-packages/werkzeug/security.py", line 64, in pbkdf2_hex
    rv = pbkdf2_bin(data, salt, iterations, keylen, hashfunc)
  File "/Users/Vim/Programs/workspace/virtualenv/flask/lib/python2.7/site-packages/werkzeug/security.py", line 104, in pbkdf2_bin
    keylen)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 174, in pbkdf2_hmac
    password = bytes(buffer(password))
TypeError: buffer object expected
```

**Comment by VimDong** [comment]
代码与学习材料 git 仓库核对过，没有问题.....
但是 Change-Email 功能跳转后报错，没有正确的响应页面。

暂时无法确定出问题的地方，以后解决。

**Comment by VimDong** [comment]
validate_on_submit 方法忘记加刮号，方法调用时无刮号，作为方法对象，因为存在，所以布尔判断为 True。

'''
    if form.validate_on_submit:
    if form.validate_on_submit():
'''
